cmake_minimum_required(VERSION 3.20)
file(MAKE_DIRECTORY "${TEST_ROOT}")
set(input "${TEST_ROOT}/input.cadu")
set(out "${TEST_ROOT}/result")
execute_process(COMMAND "${FIXTURE}" fixture "${input}" RESULT_VARIABLE code)
if(NOT code EQUAL 0)
    message(FATAL_ERROR "Fixture generation failed")
endif()
set(args "${input}" --out "${out}" --no-rs --dump-stats)
set(expected_exit 0)
if(CASE STREQUAL "collision")
    file(MAKE_DIRECTORY "${out}")
    configure_file("${input}" "${out}/avhrr_scan_log.csv" COPYONLY)
    set(input "${out}/avhrr_scan_log.csv")
    set(args "${input}" --out "${out}" --no-rs)
    set(expected_exit 1)
elseif(CASE STREQUAL "output_failure")
    file(MAKE_DIRECTORY "${out}/avhrr_scan_log.csv")
    set(expected_exit 1)
elseif(CASE STREQUAL "partial")
    list(APPEND args --max-cadus 14)
endif()
file(SHA256 "${input}" before)
execute_process(COMMAND "${DECODER}" ${args} RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
file(SHA256 "${input}" after)
if(NOT code EQUAL expected_exit OR NOT before STREQUAL after)
    message(FATAL_ERROR "Wrong exit or input changed: ${code}\n${stdout}\n${stderr}")
endif()
if(NOT expected_exit EQUAL 0)
    if(stderr STREQUAL "")
        message(FATAL_ERROR "Output error not reported")
    endif()
    return()
endif()
file(READ "${out}/stats.json" json)
string(JSON accepted GET "${json}" avhrr_scans accepted)
string(JSON rejected GET "${json}" avhrr_scans rejected)
string(JSON mode_a GET "${json}" avhrr_scans channel_3a)
string(JSON mode_b GET "${json}" avhrr_scans channel_3b)
file(STRINGS "${out}/avhrr_scan_log.csv" rows)
list(LENGTH rows row_count)
if(CASE STREQUAL "partial")
    if(NOT accepted EQUAL 0 OR NOT rejected EQUAL 0 OR NOT row_count EQUAL 1)
        message(FATAL_ERROR "Incomplete Space Packet emitted a scan")
    endif()
else()
    if(NOT accepted EQUAL 2 OR NOT rejected EQUAL 0 OR NOT mode_a EQUAL 1 OR NOT mode_b EQUAL 1 OR NOT row_count EQUAL 3)
        message(FATAL_ERROR "Wrong scan counts: ${json}")
    endif()
    foreach(i RANGE 1 2)
        list(GET rows ${i} row)
        if(NOT row MATCHES "not_applied,accepted,3[AB],9707,31556567,716,1315597,57370,2048$")
            message(FATAL_ERROR "Wrong metadata/geometry/provenance: ${row}")
        endif()
    endforeach()
endif()
