cmake_minimum_required(VERSION 3.20)
file(MAKE_DIRECTORY "${TEST_ROOT}")
set(input "${TEST_ROOT}/input.cadu")
set(out "${TEST_ROOT}/result")
set(kind clean)
if(CASE STREQUAL "rejected")
    set(kind rejected)
endif()
execute_process(COMMAND "${FIXTURE}" fixture "${input}" "${kind}" RESULT_VARIABLE code)
if(NOT code EQUAL 0)
    message(FATAL_ERROR "Cannot generate fixture")
endif()
set(args "${input}" --out "${out}" --dump-stats)
set(expected_exit 0)
set(expected_selected 2)
set(expected_previewed 2)
if(NOT CASE STREQUAL "default")
    list(APPEND args --dump-debug)
endif()
if(CASE STREQUAL "limit")
    list(APPEND args --inspect-packets 1)
    set(expected_previewed 1)
elseif(CASE STREQUAL "zero")
    list(APPEND args --inspect-packets 0)
    set(expected_previewed 0)
elseif(CASE STREQUAL "no_rs")
    list(APPEND args --no-rs)
elseif(CASE STREQUAL "rejected")
    set(expected_exit 1)
    set(expected_selected 0)
    set(expected_previewed 0)
elseif(CASE MATCHES "^collision_(csv|103|104)$")
    if(CMAKE_MATCH_1 STREQUAL "csv")
        set(name packet_log.csv)
    else()
        set(name "apid_${CMAKE_MATCH_1}_packets.bin")
    endif()
    file(MAKE_DIRECTORY "${out}/debug")
    configure_file("${input}" "${out}/debug/${name}" COPYONLY)
    set(input "${out}/debug/${name}")
    set(args "${input}" --out "${out}" --dump-debug)
    set(expected_exit 1)
elseif(CASE STREQUAL "output_failure")
    file(MAKE_DIRECTORY "${out}/debug/apid_104_packets.bin")
    set(expected_exit 1)
endif()
file(SHA256 "${input}" before)
execute_process(COMMAND "${DECODER}" ${args} RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
file(SHA256 "${input}" after)
if(NOT before STREQUAL after OR NOT "${code}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Input changed or wrong exit ${code}:\n${stdout}\n${stderr}")
endif()
if(CASE MATCHES "^collision_" OR CASE STREQUAL "output_failure")
    if(stderr STREQUAL "")
        message(FATAL_ERROR "Missing output error")
    endif()
    return()
endif()
file(READ "${out}/stats.json" json)
string(JSON schema GET "${json}" schema_version)
string(JSON selected GET "${json}" avhrr selected_packets)
string(JSON previewed GET "${json}" avhrr previewed_packets)
if(NOT schema EQUAL 6 OR NOT selected EQUAL expected_selected OR NOT previewed EQUAL expected_previewed)
    message(FATAL_ERROR "Incorrect inspection counters: ${json}")
endif()
set(expected_apid_count 1)
if(CASE STREQUAL "rejected")
    set(expected_apid_count 0)
endif()
foreach(apid IN ITEMS 103 104)
    string(JSON count GET "${json}" avhrr apids ${apid} packets)
    if(NOT count EQUAL expected_apid_count)
        message(FATAL_ERROR "Incorrect APID count")
    endif()
    if(CASE STREQUAL "default")
        if(EXISTS "${out}/debug/apid_${apid}_packets.bin")
            message(FATAL_ERROR "Default mode wrote optional binary dump")
        endif()
    else()
        file(SIZE "${out}/debug/apid_${apid}_packets.bin" size)
        if(CASE STREQUAL "rejected")
            if(NOT size EQUAL 0)
                message(FATAL_ERROR "Rejected RS packet dumped")
            endif()
        else()
            if(apid EQUAL 103)
                set(expected_size 2000)
            else()
                set(expected_size 646)
            endif()
            if(NOT size EQUAL expected_size)
                message(FATAL_ERROR "Wrong dump size for APID ${apid}")
            endif()
        endif()
    endif()
endforeach()
file(STRINGS "${out}/debug/packet_log.csv" rows)
list(LENGTH rows count)
math(EXPR expected_rows "${expected_selected} + 1")
if(NOT count EQUAL expected_rows)
    message(FATAL_ERROR "Debug log includes wrong VCID/APID or omits a packet")
endif()
if(NOT CASE STREQUAL "rejected")
    # Independent reference CVCDUs: strip 10 VCDU/M-PDU header bytes and parity.
    file(STRINGS "${REFERENCE}" frames)
    set(packet_stream "")
    foreach(i RANGE 0 2)
        list(GET frames ${i} frame)
        string(SUBSTRING "${frame}" 20 1764 zone)
        string(APPEND packet_stream "${zone}")
    endforeach()
    string(SUBSTRING "${packet_stream}" 0 4000 expected103)
    string(SUBSTRING "${packet_stream}" 4000 1292 expected104)
    foreach(apid IN ITEMS 103 104)
        if(NOT CASE STREQUAL "default")
            file(READ "${out}/debug/apid_${apid}_packets.bin" actual HEX)
            if(NOT actual STREQUAL expected${apid})
                message(FATAL_ERROR "Dump differs byte-for-byte from reference Space Packet")
            endif()
        endif()
        math(EXPR row_index "${apid} - 102")
        list(GET rows ${row_index} row)
        string(REPLACE "," ";" columns "${row}")
        list(LENGTH columns column_count)
        list(GET columns 7 logged_apid)
        list(GET columns 15 rs_status)
        list(GET columns 17 has_preview)
        list(GET columns 18 first)
        list(GET columns 19 last)
        if(NOT column_count EQUAL 20 OR NOT logged_apid EQUAL apid)
            message(FATAL_ERROR "CSV schema/APID mismatch")
        endif()
        if(CASE STREQUAL "no_rs")
            if(NOT rs_status STREQUAL "not_applied")
                message(FATAL_ERROR "Bypass incorrectly claims RS")
            endif()
        elseif(NOT rs_status STREQUAL "rs_checked")
            message(FATAL_ERROR "Missing RS provenance")
        endif()
        if(row_index LESS_EQUAL expected_previewed)
            string(SUBSTRING "${expected${apid}}" 12 128 expected_first)
            string(LENGTH "${expected${apid}}" hex_length)
            math(EXPR tail_start "${hex_length} - 32")
            string(SUBSTRING "${expected${apid}}" ${tail_start} 32 expected_last)
            string(TOUPPER "${expected_first}" expected_first)
            string(TOUPPER "${expected_last}" expected_last)
            if(NOT has_preview EQUAL 1 OR NOT first STREQUAL expected_first OR NOT last STREQUAL expected_last)
                message(FATAL_ERROR "Preview must cover complete Packet Data Field after six-byte primary header")
            endif()
        elseif(NOT has_preview EQUAL 0 OR NOT first STREQUAL "" OR NOT last STREQUAL "")
            message(FATAL_ERROR "Preview limit not respected")
        endif()
    endforeach()
    string(JSON histogram103 GET "${json}" avhrr apids 103 total_size_histogram 2000)
    string(JSON histogram104 GET "${json}" avhrr apids 104 total_size_histogram 646)
    string(JSON seq GET "${json}" avhrr apids 103 sequence_counts 0)
    string(JSON flags GET "${json}" avhrr apids 104 sequence_flags 3)
    string(JSON secondary GET "${json}" avhrr apids 104 secondary_header_flags 0)
    if(NOT histogram103 EQUAL 1 OR NOT histogram104 EQUAL 1 OR NOT seq EQUAL 1 OR NOT flags EQUAL 1 OR NOT secondary EQUAL 1)
        message(FATAL_ERROR "Histogram/sequence/flag counters differ")
    endif()
endif()
if(CASE STREQUAL "zero" AND stdout MATCHES "payload_first64_hex=")
    message(FATAL_ERROR "Zero preview still prints payload")
endif()
if(CASE STREQUAL "complete" AND NOT stdout MATCHES "payload_first64_hex=")
    message(FATAL_ERROR "Debug mode did not print payload preview")
endif()
file(READ "${out}/stats.txt" text)
if(NOT text MATCHES "APID 103 count: ${expected_apid_count}" OR NOT stdout MATCHES "APID 104 count: ${expected_apid_count}")
    message(FATAL_ERROR "Text statistics mismatch")
endif()
