cmake_minimum_required(VERSION 3.20)

# Fixtures and outputs live only under this test's build directory.
file(MAKE_DIRECTORY "${TEST_ROOT}")
string(ASCII 26 207 252 29 asm)
# Fixed prefix: version 1, SCID 12, VCID 9 XOR standard PN FF 48.
string(ASCII 188 65 prefix)
string(REPEAT "x" 1018 remainder)
set(payload "${prefix}${remainder}")
set(frame "${asm}${payload}")
set(input "${TEST_ROOT}/input.cadu")
set(out "${TEST_ROOT}/result")
file(WRITE "${input}" "${frame}${frame}${frame}")
set(args "${input}" --out "${out}")
set(expected_exit 0)
set(expected_count 3)
set(expected_eof ON)
set(expected_limit OFF)
set(expected_skipped 0)
set(expected_trailing 0)
set(check_stats ON)

if(CASE STREQUAL "help")
    set(args --help)
    set(check_stats OFF)
elseif(CASE STREQUAL "valid")
    list(APPEND args --dump-stats --verbose)
elseif(CASE STREQUAL "unicode_paths")
    set(input "${TEST_ROOT}/próba_żółć.cadu")
    set(out "${TEST_ROOT}/wynik_żółć")
    file(WRITE "${input}" "${frame}${frame}${frame}")
    set(args "${input}" --out "${out}")
elseif(CASE STREQUAL "limit")
    list(APPEND args --max-cadus 2)
    set(expected_count 2)
    set(expected_eof OFF)
    set(expected_limit ON)
elseif(CASE STREQUAL "exact_limit")
    list(APPEND args --max-cadus 3)
    set(expected_eof OFF)
    set(expected_limit ON)
elseif(CASE STREQUAL "empty")
    file(WRITE "${input}" "")
    set(expected_exit 1)
    set(expected_count 0)
elseif(CASE STREQUAL "garbage")
    string(REPEAT "x" 4096 garbage)
    file(WRITE "${input}" "${garbage}")
    set(expected_exit 1)
    set(expected_count 0)
    set(expected_skipped 3073)
    set(expected_trailing 1023)
elseif(CASE STREQUAL "truncated")
    file(WRITE "${input}" "${asm}short")
    set(expected_exit 1)
    set(expected_count 0)
    set(expected_trailing 9)
elseif(CASE STREQUAL "recovered")
    file(WRITE "${input}" "junk${frame}${frame}end")
    set(expected_count 2)
    set(expected_skipped 4)
    set(expected_trailing 3)
elseif(CASE STREQUAL "missing_input")
    set(args "${TEST_ROOT}/absent.cadu" --out "${out}")
    set(expected_exit 1)
    set(check_stats OFF)
elseif(CASE STREQUAL "output_failure")
    file(WRITE "${TEST_ROOT}/not-a-directory" "sentinel")
    set(args "${input}" --out "${TEST_ROOT}/not-a-directory/child")
    set(expected_exit 1)
    set(check_stats OFF)
elseif(CASE STREQUAL "input_collision")
    file(MAKE_DIRECTORY "${out}")
    set(input "${out}/stats.json")
    file(WRITE "${input}" "${frame}")
    set(args "${input}" --out "${out}")
    set(expected_exit 1)
    set(check_stats OFF)
elseif(CASE STREQUAL "statistics_failure")
    file(MAKE_DIRECTORY "${out}/stats.txt")
    set(expected_exit 1)
    set(check_stats OFF)
else()
    set(expected_exit 2)
    set(check_stats OFF)
    if(CASE STREQUAL "missing_out")
        set(args "${input}")
    elseif(CASE STREQUAL "unknown_option")
        list(APPEND args --no-rs)
    elseif(CASE STREQUAL "invalid_limit")
        list(APPEND args --max-cadus 12garbage)
    elseif(CASE STREQUAL "zero_limit")
        list(APPEND args --max-cadus 0)
    elseif(CASE STREQUAL "overflow_limit")
        list(APPEND args --max-cadus 18446744073709551616)
    elseif(CASE STREQUAL "negative_limit")
        list(APPEND args --max-cadus -1)
    elseif(CASE STREQUAL "missing_value")
        list(APPEND args --max-cadus --verbose)
    elseif(CASE STREQUAL "duplicate_option")
        list(APPEND args --out "${out}")
    elseif(CASE STREQUAL "extra_input")
        list(APPEND args "${input}")
    else()
        message(FATAL_ERROR "Unknown case: ${CASE}")
    endif()
endif()

file(SHA256 "${input}" input_before)
execute_process(COMMAND "${DECODER}" ${args}
    RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 20)
if(NOT "${code}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "${CASE}: expected exit ${expected_exit}, got ${code}\n${stdout}\n${stderr}")
endif()
file(SHA256 "${input}" input_after)
if(NOT input_before STREQUAL input_after)
    message(FATAL_ERROR "Input was modified")
endif()
if(CASE STREQUAL "help" AND NOT stdout MATCHES "M2: CADU derandomization")
    message(FATAL_ERROR "Help does not explain implemented scope")
endif()
if(CASE STREQUAL "valid" AND (NOT stdout MATCHES "CADUs read: 3" OR NOT stderr MATCHES "CADU 2 offset 2048"))
    message(FATAL_ERROR "Missing full statistics or verbose offsets")
endif()
if(expected_exit GREATER 0 AND stderr STREQUAL "")
    message(FATAL_ERROR "Failure has no diagnostic")
endif()
if(check_stats)
    file(READ "${out}/stats.json" json)
    file(READ "${out}/stats.txt" text)
    string(JSON stage GET "${json}" stage)
    string(JSON count GET "${json}" cadu cadus_read)
    string(JSON asm_count GET "${json}" cadu valid_asm)
    string(JSON skipped GET "${json}" cadu skipped_bytes)
    string(JSON trailing GET "${json}" cadu trailing_bytes)
    string(JSON consumed GET "${json}" cadu bytes_consumed)
    string(JSON eof GET "${json}" cadu reached_eof)
    string(JSON limited GET "${json}" stopped_by_limit)
    string(JSON input_size GET "${json}" input_size)
    file(SIZE "${input}" actual_size)
    math(EXPR accounted "${count} * 1024 + ${skipped} + ${trailing}")
    if(NOT stage STREQUAL "derandomization_diagnostics" OR NOT count EQUAL expected_count
       OR NOT asm_count EQUAL expected_count OR NOT skipped EQUAL expected_skipped
       OR NOT trailing EQUAL expected_trailing OR NOT consumed EQUAL accounted
       OR NOT input_size EQUAL actual_size OR NOT eof STREQUAL expected_eof
       OR NOT limited STREQUAL expected_limit)
        message(FATAL_ERROR "Unexpected statistics:\n${json}")
    endif()
    if(eof AND NOT consumed EQUAL input_size)
        message(FATAL_ERROR "EOF byte accounting does not match file size")
    endif()
    if(NOT text MATCHES "CADUs read: ${expected_count}")
        message(FATAL_ERROR "Text statistics disagree with JSON")
    endif()
    string(JSON rs GET "${json}" rs_applied)
    if(rs)
        message(FATAL_ERROR "M2 must not claim RS correction")
    endif()
    if(expected_count GREATER 0)
        string(JSON vcid GET "${json}" vcids_after 9)
        string(JSON version GET "${json}" versions_after 1)
        string(JSON spacecraft GET "${json}" spacecraft_after 12)
        if(NOT vcid EQUAL expected_count OR NOT version EQUAL expected_count OR NOT spacecraft EQUAL expected_count)
            message(FATAL_ERROR "Incorrect derandomized header diagnostics")
        endif()
    endif()
endif()
message(STATUS "PASS ${CASE}")
