cmake_minimum_required(VERSION 3.20)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run_id)
set(root "${TEST_ROOT}/${run_id}")
file(MAKE_DIRECTORY "${root}")
set(input "${root}/input.cadu")
set(out "${root}/result")
set(fixture_args fixture "${input}")
if(CASE STREQUAL "bad_vpc")
    list(APPEND fixture_args bad_vpc)
endif()
execute_process(COMMAND "${FIXTURE}" ${fixture_args} RESULT_VARIABLE code)
if(NOT code EQUAL 0)
    message(FATAL_ERROR "Fixture failed")
endif()
set(expected_exit 0)
if(CASE STREQUAL "existing" OR CASE STREQUAL "collision")
    file(MAKE_DIRECTORY "${out}/avhrr")
    if(CASE STREQUAL "collision")
        configure_file("${input}" "${out}/avhrr/input.cadu" COPYONLY)
        set(input "${out}/avhrr/input.cadu")
    else()
        file(WRITE "${out}/avhrr/sentinel" "keep")
    endif()
    set(expected_exit 1)
endif()
set(args "${input}" --out "${out}" --no-rs --dump-stats)
if(CASE STREQUAL "partial")
    list(APPEND args --max-cadus 14)
endif()
file(SHA256 "${input}" before)
execute_process(COMMAND "${DECODER}" ${args} RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
file(SHA256 "${input}" after)
if(NOT code EQUAL expected_exit OR NOT before STREQUAL after)
    message(FATAL_ERROR "Exit/input mismatch: ${code}\n${stdout}\n${stderr}")
endif()
if(expected_exit EQUAL 1)
    if(EXISTS "${out}/stats.json" OR EXISTS "${out}/debug/packet_log.csv")
        message(FATAL_ERROR "Nonempty image directory rejected after truncating other outputs")
    endif()
    if(CASE STREQUAL "existing")
        file(READ "${out}/avhrr/sentinel" sentinel)
        if(NOT sentinel STREQUAL "keep")
            message(FATAL_ERROR "Existing image output overwritten")
        endif()
    endif()
    return()
endif()
file(READ "${out}/stats.json" json)
string(JSON files GET "${json}" images files)
string(JSON scans GET "${json}" images scans)
file(GLOB_RECURSE pgms "${out}/avhrr/*.pgm")
list(LENGTH pgms actual_files)
if(CASE STREQUAL "partial")
    if(NOT files EQUAL 0 OR NOT scans EQUAL 0 OR NOT actual_files EQUAL 0)
        message(FATAL_ERROR "Partial scan created images")
    endif()
elseif(CASE STREQUAL "bad_vpc")
    string(JSON rejected GET "${json}" avhrr_scans rejected)
    if(NOT files EQUAL 5 OR NOT scans EQUAL 1 OR NOT actual_files EQUAL 5 OR NOT rejected EQUAL 1
       OR EXISTS "${out}/avhrr/scid_11_vcid_9_replay_0/ch3a_raw.pgm")
        message(FATAL_ERROR "Invalid payload entered image output")
    endif()
else()
    if(NOT files EQUAL 6 OR NOT scans EQUAL 2 OR NOT actual_files EQUAL 6)
        message(FATAL_ERROR "Wrong image count: ${json}")
    endif()
    execute_process(COMMAND "${IMAGE_TESTS}" cli_check "${out}" RESULT_VARIABLE code)
    if(NOT code EQUAL 0)
        message(FATAL_ERROR "PGM sample preservation failed")
    endif()
endif()
if(scans GREATER 0)
    file(READ "${out}/avhrr/scid_11_vcid_9_replay_0/metadata.json" meta)
    string(JSON count GET "${meta}" scan_count)
    string(JSON width GET "${meta}" width)
    string(JSON maxval GET "${meta}" maxval)
    string(JSON rs GET "${meta}" rs_applied)
    if(NOT count EQUAL scans OR NOT width EQUAL 2048 OR NOT maxval EQUAL 1023 OR rs)
        message(FATAL_ERROR "Invalid metadata: ${meta}")
    endif()
endif()
file(GLOB_RECURSE spools "${out}/avhrr/*.tmp")
if(spools)
    message(FATAL_ERROR "Raster spools retained")
endif()
