cmake_minimum_required(VERSION 3.20)
file(MAKE_DIRECTORY "${TEST_ROOT}")
set(input "${TEST_ROOT}/input.cadu")
set(out "${TEST_ROOT}/result")
set(fixture_case fixture)
if(CASE STREQUAL "gap" OR CASE STREQUAL "resync" OR CASE STREQUAL "partial")
    set(fixture_case "fixture_${CASE}")
endif()
execute_process(COMMAND "${FIXTURE}" "${fixture_case}" "${input}" RESULT_VARIABLE code)
if(NOT code EQUAL 0)
    message(FATAL_ERROR "Cannot generate packet fixture")
endif()
set(args "${input}" --out "${out}" --no-rs --dump-stats)
if(CASE STREQUAL "limit")
    list(APPEND args --max-cadus 2)
elseif(CASE STREQUAL "collision")
    file(MAKE_DIRECTORY "${out}")
    configure_file("${input}" "${out}/packet_log.csv" COPYONLY)
    set(input "${out}/packet_log.csv")
    set(args "${input}" --out "${out}" --no-rs)
elseif(CASE STREQUAL "output_failure")
    file(MAKE_DIRECTORY "${out}/packet_log.csv")
endif()
file(SHA256 "${input}" before)
execute_process(COMMAND "${DECODER}" ${args}
    RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
file(SHA256 "${input}" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Input overwritten")
endif()
if(CASE STREQUAL "collision" OR CASE STREQUAL "output_failure")
    if(NOT code EQUAL 1 OR stderr STREQUAL "")
        message(FATAL_ERROR "Expected output error: ${code}\n${stderr}")
    endif()
else()
    if(NOT code EQUAL 0)
        message(FATAL_ERROR "Decoder failed: ${code}\n${stdout}\n${stderr}")
    endif()
    file(READ "${out}/stats.json" json)
    string(JSON stage GET "${json}" stage)
    string(JSON schema GET "${json}" schema_version)
    string(JSON packets GET "${json}" packets reconstructed)
    string(JSON truncated GET "${json}" packets truncated_packets)
    string(JSON rs GET "${json}" rs_applied)
    if(NOT stage STREQUAL "space_packets_no_rs" OR NOT schema EQUAL 4 OR rs)
        message(FATAL_ERROR "Incorrect stage/schema/RS status")
    endif()
    file(STRINGS "${out}/packet_log.csv" rows)
    list(LENGTH rows row_count)
    if(CASE STREQUAL "complete")
        string(JSON bytes GET "${json}" packets reconstructed_bytes)
        string(JSON vc9 GET "${json}" packets by_vcid 9)
        string(JSON invalid GET "${json}" packets invalid_headers)
        string(JSON mismatches GET "${json}" packets boundary_mismatches)
        if(NOT packets EQUAL 2 OR NOT truncated EQUAL 0 OR NOT row_count EQUAL 3
           OR NOT bytes EQUAL 2646 OR NOT vc9 EQUAL 2 OR NOT invalid EQUAL 0 OR NOT mismatches EQUAL 0)
            message(FATAL_ERROR "Bad complete reassembly statistics: ${json}")
        endif()
        list(GET rows 1 first)
        list(GET rows 2 second)
        if(NOT first STREQUAL "0,11,9,0,10,12,103,3,291,1,2000,not_applied"
           OR NOT second STREQUAL "1,11,9,0,12,12,104,3,291,1,646,not_applied")
            message(FATAL_ERROR "Incorrect packet provenance/header log: ${rows}")
        endif()
    elseif(CASE STREQUAL "gap" OR CASE STREQUAL "resync")
        if(NOT packets EQUAL 1 OR NOT truncated EQUAL 1 OR NOT row_count EQUAL 2)
            message(FATAL_ERROR "Lost-frame/alignment recovery failed: ${json}")
        endif()
        list(GET rows 1 recovered)
        if(NOT recovered MATCHES ",104,3,291,1,646,not_applied$")
            message(FATAL_ERROR "Recovered incorrect packet: ${rows}")
        endif()
        if(CASE STREQUAL "resync")
            string(JSON resyncs GET "${json}" cadu resyncs)
            if(NOT resyncs EQUAL 1)
                message(FATAL_ERROR "Resync fixture did not exercise recovery")
            endif()
        endif()
    else()
        string(JSON discarded GET "${json}" packets discarded_partial_bytes)
        if(NOT packets EQUAL 0 OR NOT truncated EQUAL 1 OR NOT row_count EQUAL 1 OR NOT discarded EQUAL 1764)
            message(FATAL_ERROR "Processing-limit partial was hidden or emitted: ${json}")
        endif()
    endif()
    file(READ "${out}/stats.txt" text)
    if(NOT text MATCHES "reconstructed: ${packets}" OR NOT stdout MATCHES "truncated_packets: ${truncated}")
        message(FATAL_ERROR "Text/JSON statistics disagree")
    endif()
endif()
