cmake_minimum_required(VERSION 3.20)
file(MAKE_DIRECTORY "${TEST_ROOT}")
set(input "${TEST_ROOT}/input.cadu")
set(out "${TEST_ROOT}/result")
execute_process(COMMAND "${FIXTURE}" fixture "${input}" "${CASE}" RESULT_VARIABLE generated)
if(NOT generated EQUAL 0)
    message(FATAL_ERROR "Cannot generate RS fixture")
endif()
set(args "${input}" --out "${out}" --dump-stats --verbose)
set(expected_exit 0)
set(expected_packets 3)
set(expected_good 4)
set(expected_corrected 0)
set(expected_bad 0)
set(expected_count 4)
set(expected_truncated 0)
set(expected_duplicates 0)
if(CASE STREQUAL "corrected")
    set(expected_good 0)
    set(expected_corrected 4)
elseif(CASE STREQUAL "recovery" OR CASE STREQUAL "duplicate_recovery")
    set(expected_good 3)
    set(expected_bad 1)
    set(expected_packets 2)
    set(expected_truncated 1)
    if(CASE STREQUAL "duplicate_recovery")
        set(expected_good 4)
        set(expected_count 5)
        set(expected_duplicates 1)
    endif()
elseif(CASE STREQUAL "rejected")
    set(expected_good 0)
    set(expected_bad 4)
    set(expected_packets 0)
    set(expected_exit 1)
elseif(CASE STREQUAL "limit")
    list(APPEND args --max-cadus 2)
    set(expected_good 2)
    set(expected_count 2)
    set(expected_packets 0)
    set(expected_truncated 1)
elseif(CASE STREQUAL "no_rs")
    list(APPEND args --no-rs)
elseif(CASE MATCHES "^collision_(rs|vcdu|packet)$")
    set(name "${CMAKE_MATCH_1}_log.csv")
    file(MAKE_DIRECTORY "${out}")
    configure_file("${input}" "${out}/${name}" COPYONLY)
    set(input "${out}/${name}")
    set(args "${input}" --out "${out}")
    set(expected_exit 1)
elseif(CASE STREQUAL "log_failure")
    file(MAKE_DIRECTORY "${out}/rs_log.csv")
    set(expected_exit 1)
elseif(NOT CASE STREQUAL "clean")
    message(FATAL_ERROR "Unknown RS CLI case")
endif()
file(SHA256 "${input}" before)
execute_process(COMMAND "${DECODER}" ${args} RESULT_VARIABLE code
    OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
file(SHA256 "${input}" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Input modified")
endif()
if(NOT "${code}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Expected ${expected_exit}, got ${code}\n${stdout}\n${stderr}")
endif()
if(expected_exit AND stderr STREQUAL "")
    message(FATAL_ERROR "Missing error diagnostic")
endif()
if(CASE MATCHES "^collision_" OR CASE STREQUAL "log_failure")
    return()
endif()
file(READ "${out}/stats.json" json)
string(JSON stage GET "${json}" stage)
string(JSON applied GET "${json}" rs_applied)
string(JSON schema GET "${json}" schema_version)
string(JSON packets GET "${json}" packets reconstructed)
string(JSON truncated GET "${json}" packets truncated_packets)
string(JSON duplicates GET "${json}" packets duplicate_frames)
string(JSON count GET "${json}" cadu cadus_read)
if(NOT schema EQUAL 9 OR NOT packets EQUAL expected_packets OR NOT count EQUAL expected_count
   OR NOT truncated EQUAL expected_truncated OR NOT duplicates EQUAL expected_duplicates)
    message(FATAL_ERROR "Incorrect packet/frame statistics: ${json}")
endif()
if(CASE STREQUAL "no_rs")
    if(applied OR NOT stage STREQUAL "space_packets_no_rs")
        message(FATAL_ERROR "Bypass claimed correction")
    endif()
    string(JSON rs ERROR_VARIABLE missing GET "${json}" rs)
    if(NOT missing)
        message(FATAL_ERROR "Bypass emitted RS counts")
    endif()
else()
    if(NOT applied OR NOT stage STREQUAL "space_packets_rs")
        message(FATAL_ERROR "Wrong RS mode")
    endif()
    string(JSON good GET "${json}" rs good_frames)
    string(JSON corrected GET "${json}" rs corrected_frames)
    string(JSON bad GET "${json}" rs uncorrectable_frames)
    string(JSON headers GET "${json}" frames headers)
    math(EXPR accepted "${good} + ${corrected}")
    if(NOT good EQUAL expected_good OR NOT corrected EQUAL expected_corrected
       OR NOT bad EQUAL expected_bad OR NOT headers EQUAL accepted)
        message(FATAL_ERROR "RS counts or rejected-frame isolation failed: ${json}")
    endif()
    foreach(lane RANGE 0 3)
        string(JSON symbols GET "${json}" rs corrected_symbols_per_lane ${lane})
        string(JSON failures GET "${json}" rs uncorrectable_lanes ${lane})
        set(expected_symbols 0)
        set(expected_failures 0)
        if(CASE STREQUAL "corrected")
            set(expected_symbols 64)
        elseif((CASE STREQUAL "recovery" OR CASE STREQUAL "duplicate_recovery") AND lane EQUAL 1)
            set(expected_symbols 1)
        endif()
        if(lane EQUAL 0)
            set(expected_failures ${expected_bad})
        endif()
        if(NOT symbols EQUAL expected_symbols OR NOT failures EQUAL expected_failures)
            message(FATAL_ERROR "Wrong lane statistics: ${json}")
        endif()
    endforeach()
endif()
file(STRINGS "${out}/rs_log.csv" rs_rows)
list(LENGTH rs_rows rs_count)
math(EXPR expected_rows "${expected_count} + 1")
if(NOT rs_count EQUAL expected_rows)
    message(FATAL_ERROR "RS log must contain every CADU, including rejected ones")
endif()
foreach(row IN LISTS rs_rows)
    string(REPLACE "," ";" columns "${row}")
    list(LENGTH columns column_count)
    if(NOT column_count EQUAL 7)
        message(FATAL_ERROR "Malformed RS CSV row: ${row}")
    endif()
endforeach()
file(STRINGS "${out}/packet_log.csv" packet_rows)
list(LENGTH packet_rows row_count)
math(EXPR expected_rows "${expected_packets} + 1")
if(NOT row_count EQUAL expected_rows)
    message(FATAL_ERROR "Wrong packet log size")
endif()
set(status rs_checked)
if(CASE STREQUAL "no_rs")
    set(status not_applied)
endif()
if(expected_packets EQUAL 3)
    list(GET packet_rows 1 first)
    list(GET packet_rows 2 second)
    list(GET packet_rows 3 third)
    if(NOT first STREQUAL "0,12,9,0,0,2,103,3,0,0,2000,${status}"
       OR NOT second STREQUAL "1,12,9,0,2,2,104,3,0,0,646,${status}"
       OR NOT third STREQUAL "2,12,9,0,3,3,105,3,0,0,882,${status}")
        message(FATAL_ERROR "Incorrect corrected packet headers/boundaries: ${packet_rows}")
    endif()
elseif(expected_packets EQUAL 2)
    list(GET packet_rows 1 first)
    list(GET packet_rows 2 second)
    if(NOT first STREQUAL "0,12,9,0,2,2,104,3,0,0,646,${status}"
       OR NOT second STREQUAL "1,12,9,0,3,3,105,3,0,0,882,${status}")
        message(FATAL_ERROR "RS rejection did not recover at next FHP: ${packet_rows}")
    endif()
endif()
file(READ "${out}/vcdu_log.csv" vcdu_log)
if(CASE STREQUAL "corrected" AND NOT vcdu_log MATCHES ",corrected,1,12,9,")
    message(FATAL_ERROR "Frame log did not use corrected header")
endif()
file(READ "${out}/stats.txt" text)
if(NOT text MATCHES "reconstructed: ${expected_packets}" OR NOT stdout MATCHES "reconstructed: ${expected_packets}")
    message(FATAL_ERROR "Text/JSON counts disagree")
endif()
